nome = input("digite seu nome: ")
print("Opção 1: soma ")
print("Opção 2: subtração ")
print("Opção 3: divisão ")
print("Opção 4: multiplicação ")
print("Opção 5: potenciação ")
opcao = input("digite a opção desejada: ")